/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#22C55E",
        deepGreen: "#0D3B2E",
        sage: "#6B8C7A",
        white: "#FFFFFF",
        mist: "#E5EDE8",
        mint: "#F0FDF4",
        snow: "#F4F8F5",
        black: "#000000",
        aquaMint: "#D1FAE5",
        forest: "#2D4A38",
        success: "#22C55E",
        successSoft: "#74E6A1",
        muted: "#9AA6B2",
        light: {
          text: "#000000",
          background: "#FFFFFF",
          backgroundElement: "#F0F0F3",
          backgroundSelected: "#E0E1E6",
          textSecondary: "#60646C",
        },
        dark: {
          text: "#FFFFFF",
          background: "#000000",
          backgroundElement: "#212225",
          backgroundSelected: "#2E3135",
          textSecondary: "#B0B4BA",
        },
      },
      fontFamily: {
        SR: ["SoraR"],
        SB: ["SoraB"],
        SSB: ["SoraSB"],
        SM: ["SoraM"],
        SL: ["SoraL"],
        SEL: ["SoraEL"],
        SEB: ["SoraEB"],
        ST: ["SoraT"],
        FR: ["SoraR"],
        FB: ["SoraB"],
        FSB: ["SoraSB"],
        FM: ["SoraM"],
        FL: ["SoraL"],
        FEB: ["SoraEB"],
        FBL: ["SoraEB"],
        FI: ["SoraR"],
        FBI: ["SoraB"],
        FBLI: ["SoraEB"],
        FEBI: ["SoraEB"],
        FLI: ["SoraL"],
        FMI: ["SoraM"],
        FSBI: ["SoraSB"],
        sans: ["SoraR"],
        "sans-medium": ["SoraM"],
        "sans-semibold": ["SoraSB"],
        "sans-bold": ["SoraB"],
      },
      spacing: {
        half: "2px",
        one: "4px",
        two: "8px",
        three: "16px",
        four: "24px",
        five: "32px",
        six: "64px",
        bottomTabIos: "50px",
        bottomTabAndroid: "80px",
      },
      borderRadius: {
        input: "14px",
        card: "16px",
        sheet: "22px",
        pill: "9999px",
      },
      maxWidth: {
        content: "800px",
      },
      boxShadow: {
        soft: "0 12px 32px rgba(13, 59, 46, 0.08)",
      },
    },
  },
  plugins: [],
};
